import belgianWaff from "./assets/belgianWaff.jpg";
import benny from "./assets/benny.jpg";
import breakfastWaff from "./assets/breakfastWaffle.jpeg";
import chickWaff from "./assets/chickWaff.jpg";
import cinnBun from "./assets/cinnBun.jpg";
import frenchT from "./assets/frenchToast.jpg";
import huevos from "./assets/huevos.jpg";
import pulledPork from "./assets/pulledPorkHash";
import veganSausage from "./assets/veganSausageTofu.jpg";
